apiVersion: openinfradev.github.com/v1
kind: HelmValuesTransformer
metadata:
  name: site

global:
  nodeSelector:
    taco-lma: enabled
  clusterName: cluster.local
  storageClassName: rbd
  repository: https://openinfradev.github.io/hanu-helm-repo/
  serviceScrapeInterval: 30s

charts:
- name: prometheus-operator
  override:
    prometheusOperator.nodeSelector: $(nodeSelector)

- name: prometheus
  override:
    kubeEtcd.endpoints:
    - 172.27.1.222
    prometheus.prometheusSpec.storageSpec.volumeClaimTemplate.spec.storageClassName: $(storageClassName)
    prometheus.prometheusSpec.storageSpec.volumeClaimTemplate.spec.resources.requests.storage: 10Gi
    prometheus.prometheusSpec.retention: 2d
    prometheus.prometheusSpec.externalLabels.taco_cluster: dev
    prometheus.prometheusSpec.nodeSelector: $(nodeSelector)
    
- name: prometheus-fed-master
  override:
    alertmanager.alertmanagerSpec.nodeSelector: $(nodeSelector)
    alertmanager.alertmanagerSpec.retention: 2h
    alertmanager.config.global.slack_api_url: https://hooks.slack.com/services/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
    prometheus.prometheusSpec.nodeSelector: $(nodeSelector)
    prometheus.prometheusSpec.storageSpec.volumeClaimTemplate.spec.storageClassName: $(storageClassName)
    prometheus.prometheusSpec.storageSpec.volumeClaimTemplate.spec.resources.requests.storage: 20Gi
  
- name: kube-state-metrics
  override:
    nodeSelector: $(nodeSelector)

- name: prometheus-pushgateway
  override:
    nodeSelector: $(nodeSelector)

- name: prometheus-process-exporter
  source:
    repository: $(repository)

- name: eck-resource
  override:
    kibana.nodeSelector: $(nodeSelector)
    
    elasticsearch.nodeSets.master.nodeSelector: $(nodeSelector)
    elasticsearch.nodeSets.master.count: 1
    elasticsearch.nodeSets.master.javaOpts: "-Xms1g -Xmx1g"
    elasticsearch.nodeSets.master.limitCpu: 2
    elasticsearch.nodeSets.master.limitMem: 4Gi
    elasticsearch.nodeSets.master.pvc.storageClassName: $(storageClassName)
    elasticsearch.nodeSets.master.pvc.size: 1Gi

    elasticsearch.nodeSets.hotdata.nodeSelector: $(nodeSelector)
    elasticsearch.nodeSets.hotdata.count: 1
    elasticsearch.nodeSets.hotdata.javaOpts: "-Xms1g -Xmx1g"
    elasticsearch.nodeSets.hotdata.limitCpu: 2
    elasticsearch.nodeSets.hotdata.limitMem: 2Gi
    elasticsearch.nodeSets.hotdata.pvc.storageClassName: $(storageClassName)
    elasticsearch.nodeSets.hotdata.pvc.size: 10Gi

    elasticsearch.nodeSets.client.enabled: false

- name: grafana
  override:
    adminPassword: password
    persistence.storageClassName: $(storageClassName)

- name: fluentbit-operator
  source:
    repository: $(repository)
  override:
    global.base_cluster_url: $(clusterName)
    fluentbitOperator.nodeSelector: $(nodeSelector)
    logExporter.nodeSelector: $(nodeSelector)

- name: fluentbit
  source:
    repository: $(repository)
  override:
    global.base_cluster_url: $(clusterName)
    global.nodeSelector: $(nodeSelector)
    fluentbit.clusterName: $(clusterName)
    fluentbit.outputs.es.host: taco-elasticsearch-es-http.lma.svc.$(clusterName)
    fluentbit.outputs.kafka:
      enabled: false
    fluentbit.esTemplate.url: https://taco-elasticsearch-es-http.lma.svc.$(clusterName):9200
    fluentbit.nodeSelector: $(nodeSelector)
    fluentbit.targetLogs:
       - bufferChunkSize: 2M
         bufferMaxSize: 5M
         do_not_store_as_default: true
         index: container
         memBufLimit: 20MB
         multi_index:
         - index: platform
           key: $kubernetes['namespace_name']
           value: kube-system|lma|fed|argo|openstack|istio-system|istio-services|trident|registry
         name: dockerlog
         parser: docker
         path: /var/log/containers/*.log
         tag: kube.*
         type: fluent
       - index: syslog
         name: syslog
         parser: syslog-rfc5424
         path: /var/log/syslog
         tag: syslog.*
         type: syslog

- name: addons
  source:
    repository: $(repository)
  override:
    SPECIAL_VALUE: SPECIAL
    serviceMonitor.trident:
      enabled: false
      interval: $(serviceScrapeInterval)
    serviceMonitor.kubelet.interval: 30s
    serviceMonitor.additionalScrapeConfigs:

- name: fed-addons
  source:
    repository: $(repository)
  override:
    metricbeat.elasticsearch.host: https://taco-elasticsearch-es-http.lma.svc.$(clusterName):9200
    metricbeat.kibana.host: taco-kibana-dashboard-kb-http.lma.svc.$(clusterName):5601
    metricbeat.prometheus.hosts:
    - fed-master-prometheus.fed.svc.$(clusterName):9090
    # tacoWatcher.host: taco-watcher.fed.svc.$(clusterName)
    # tacoWatcher.joinCluster.body.kibanaUrl: http://taco-kibana-dashboard-kb-http.lma.svc.$(clusterName):5601
    # tacoWatcher.joinCluster.body.grafanaUrl: http://grafana.fed.svc.$(clusterName)
    # tacoWatcher.joinCluster.body.k8sUrl: https://kubernetes.default.svc.$(clusterName)
    kibanaInit.url: http://taco-kibana-dashboard-kb-http.lma.svc.$(clusterName):5601

- name: prometheus-adapter
  override:
    nodeSelector: $(nodeSelector)

- name: kubernetes-event-exporter
  source:
    repository: $(repository)
  override:
    conf.default.hosts:
    - "https://taco-elasticsearch-es-http.lma.svc.$(clusterName):9200"
